# # Use postgres/example user/password credentials
version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    restart: always
    ports: 
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./db:/docker-entrypoint-initdb.d